[package]
name = "statistics1v"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
phf = "0.11.2"
phf_macros = "0.11.2"
regex = "1.10.2"
thiserror = "1.0.51"
